### ISSUE TITLE
Unable to allocate 139. MiB for an array with shape (9131294, 2) and data type float64

### ISSUE THREAD

**Issue by GoodnessEzeokafor** [sergree/matchering#19] opened 2020-03-22 11:40 UTC
Request Method: | POST
-- | --
http://204.48.23.194/dashboard/track/1/
3.0.3
MemoryError
Unable to allocate 139. MiB for an array with shape (9131294, 2) and data type float64
/home/goodness/Gorealla/lib/python3.6/site-packages/numpy/lib/function_base.py in copy, line 775
/home/goodness/Gorealla/bin/python
3.6.9
['/home/goodness/Gorealla/src',  '/home/goodness/Gorealla/bin',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/home/goodness/Gorealla/lib/python3.6/site-packages',  '/home/goodness/Gorealla/src/paystack']
Sun, 22 Mar 2020 12:37:57 +0100

**Comment by sergree** [comment] 2020-03-22 11:58
Hello.
Duplicate of:
https://github.com/sergree/matchering/issues/18

Make sure that your virtual server has at least 4 GB of RAM.

**Closed** 2020-03-22 12:11 UTC
