### ISSUE TITLE
Getting the mastered track

### ISSUE THREAD

**Issue by GoodnessEzeokafor** [sergree/matchering#10] opened 2020-02-10 16:50 UTC
Hello i'm back again
is there a way to get the mastered tracks outside the mg.process function

**Comment by GoodnessEzeokafor** [comment] 2020-02-10 18:38
and also do u have any tutorial on how to use this tool with Amazon s3

**Comment by sergree** [comment] 2020-02-10 19:26
Hi. As I understand it, you need a numpy array?

**Comment by sergree** [comment] 2020-02-11 08:07
> and also do u have any tutorial on how to use this tool with Amazon s3
no, I doesnt have it. I don't have a good experience with cloud services. I think this question is not related to the library, but rather to the architecture of your web application. the library can read local files, process them, and save the result to a local file

**Comment by sergree** [comment] 2020-02-18 06:50
I close this because there is no answer. Create a new issue if the problem is relevant.

**Closed by sergree** 2020-02-18 06:50 UTC
